# Generated by Django 3.0.2 on 2020-01-26 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200126_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartuser',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.City'),
        ),
        migrations.AlterField(
            model_name='kartuser',
            name='dob',
            field=models.DateField(),
        ),
    ]
